### ISSUE TITLE
RGB is not defined in pykms when building with no utils

### ISSUE THREAD

**Issue by cshaw-velo-ai** [tomba/kmsxx#69]
Hi.  Building the Python bindings with libutils and utils set to false, there is a Python name error on the `RGB` type:
```
>>> import pykms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pykms/__init__.py", line 10, in <module>
    red = RGB(255, 0, 0)
NameError: name 'RGB' is not defined
```
It looks like `__init__.py` is using the RGB type but that is only defined if you bring in the utils?

**Comment by tomba** [comment]
This should be fixed in master now.
